import tkinter
def convert():
    a = input.get()
    b =1.61*int(a)
    t3.config(text=int(b))
window= tkinter.Tk()
window.title("Mile to Km Convertor")
window.minsize(height="50",width="100")
window.config(padx=20,pady=20)
input = tkinter.Entry()
input.grid(row = 0, column = 1)
input.config(width=7)
t1 = tkinter.Label(text="Miles")
t1.grid(row = 0,column= 2)
t2 = tkinter.Label(text="is equal to")
t2.grid(row = 1,column= 0)
t3 = tkinter.Label(text="0")
t3.grid(row = 1,column= 1)
t4 = tkinter.Label(text="Km")
t4.grid(row = 1,column= 2)
button = tkinter.Button(text="Calculate",command=convert)
button.grid(row=2,column=1)
tkinter.mainloop()